export const COLORS = {
  background: '#F0F4FF',
  primary: '#6C3CE1',
  secondary: '#FF6B6B',
  accent: '#FFD93D',
  star: '#FFB800',
  success: '#4CAF50',
  error: '#F44336',
  white: '#FFFFFF',
  text: '#1A1A2E',
  textSecondary: '#6B7280',
  canvasBg: '#FFFFFF',
  canvasBorder: '#6C3CE1',
  timerHigh: '#4CAF50',
  timerMed: '#FF9800',
  timerLow: '#F44336',
};

export const DIFFICULTY = {
  SCHLUESSEL: {
    key: 'SCHLUESSEL',
    label: 'Schlüssel-Reihen',
    emoji: '🗝️',
    description: '1er, 2er, 5er und 10er Reihe',
    allowedFactors: [1, 2, 5, 10],
    maxFactor: 10,
    timeSeconds: 60,
    color: '#00897B',
  },
  EASY: {
    key: 'EASY',
    label: 'Leicht',
    emoji: '🌟',
    description: '1er bis 5er Reihe',
    maxFactor: 5,
    timeSeconds: 60,
    color: '#4CAF50',
  },
  MEDIUM: {
    key: 'MEDIUM',
    label: 'Mittel',
    emoji: '⭐',
    description: '1er bis 10er Reihe',
    maxFactor: 10,
    timeSeconds: 60,
    color: '#FF9800',
  },
  HARD: {
    key: 'HARD',
    label: 'Schwer',
    emoji: '🔥',
    description: 'Alles durcheinander – Tempo!',
    maxFactor: 10,
    timeSeconds: 45,
    color: '#F44336',
  },
};
